---
title: "[C++] RAII (Resource Acquisition Is Initialization)"
excerpt: "기초적인 RAII에 대해 알아보자"

categories:
  - Cpp
tags:
  - [Cpp]

toc : true
toc_sticky: true

last_modified_at: 2021-07-31
---

<mark style="background-color: #3e3e3e; color: orange;">RAII</mark>는 C++설계(디자인) 패턴 중 하나이다.   
직역하면 <U>리소스 획득이 초기화되다</U> 라고 해석할 수 있다.

동적 프로그래밍을 할 때, 할당된 메모리를 사용한다.   
이때 여러 예외(exception)와 실수로 인해 `메모리 누수`가 일어날 수 있다.

또는 파일을 `open`, `close`해야 하는데, `close`하지 못하는 경우도 일어날 수 있다.

메모리를 할당하고 해제하지 않으면 결국 메모리 부족으로 프로그램이 깨질 수 있다.

이러한 `메모리 누수`의 문제를 안전하게 관리하기 위해 만든 것들이 있는데,   
이러한 것들을 통틀어 <mark style="background-color: #3e3e3e; color: orange;">RAII</mark>라고 한다.

> 여담으로 C++ 이후 나온 언어들의 대부분에는   
가비지 컬랙터(Garbage Collector - GC)가 기본적으로 내장된다.   
이는 자원 청소기와 같은 개념으로,   
더 이상 쓰이지 않는 리소스를 자동으로 해제해주는 역할을 한다.

## RAII 개념

```cpp
class Test
{
public:
  ~Test()
  {
    std::cout << "Test 소멸자" << std::endl;
  }
};

void func()
{
  throw "exception";
}

int main()
{
  try
  {
    Test t;
    func();
  }
  catch(const char *e)
  {
    std::cout << e << std::endl;
  }
}


//  Test 소멸자
//  exception
```

* 위의 예외 처리 구문은 문제없이 동작한다.   
하지만 `try`에서 동적 할당의 객체를 생성하면 문제가 발생한다.

```cpp
int main()
{
  try
  {
    Test *t = new Test;
    func();
  }
  catch(const char *e)
  {
    std::cout << e << std::endl;
  }
}

//  exception
```

* 객체가 정상적으로 해제되지 않아 소멸자가 호출되지 않는다.   
동적 할당된 객체를 `delete`로 해제해 주지 않았기 때문이다.

___

물론 범위 밖에서 포인터의 선언하여 해결할 수도 있다.

```cpp
class Test
{
public:
  ~Test()
  {
    std::cout << "Test 소멸자" << std::endl;
  }
};

void func()
{
  throw "exception";
}

int main()
{
  Test *t = nullptr;

  try
  {
    t = new Test;
    func();
    delete t;
    t = nullptr;
  }

  catch(const char *e)
  {
    delete t;
    t = nullptr;
    std::cout << e << std::endl;
  }
}
```

하지만 예외가 많아지고, `catch`를 여러 번 정의해야 한다면   
해제를 여러번 작성해야 한다.

또는 여러 번의 동적 할당을 해야 한다면 그만큼 해제를 여러 번 해야 한다.

이는 불편하면서 실수를 유발할 수 있다.

___

<mark style="background-color: #3e3e3e; color: orange;">RAII</mark>는 이러한 상황에서 쓰일 수 있다.

```cpp
class Test
{
public:
  ~Test()
  {
    std::cout << "Test 소멸자" << std::endl;
  }
};

class Block
{
public:
  Test *t;

  Block()
  {
    t = new Test;
  }
  ~Block()
  {
    delete t;
  }
};

void func()
{
  throw "exception";
}

int main()
{
  try
  {
    Block block;
    func();
  }

  catch(const char *e)
  {
    std::cout << e << std::endl;
  }
}


//  Test 소멸자
//  exception
```

* 클래스의 정적 할당된 객체가 범위를 벗어나면   
자동으로 소멸자가 호출되는 것을 이용하여   
내부의 동적 할당을 자동으로 해제해 주도록 만들었다.

이렇게 안전하게 리소스를 해제하는 것을 <mark style="background-color: #3e3e3e; color: orange;">RAII</mark>라고 한다.

___

메모리를 잘못된 방식으로 관리하게 되면 크게 두 가지 문제가 발생할 수 있다.

* 메모리를 해제하지 않아 메모리 누수가 일어난다. (RAII로 해결할 수 있다.)
* 이미 해제된 메모리를 참조한다.

## unique_ptr

이미 해제된 메모리를 참조하는 문제는 아래와 같은 경우 일어날 수 있다.

```cpp
Test *t = new Test;
Test *t2 = t;

//...

delete t;
delete t2;
```

* 객체 `t`를 해제하면 `t2` 객체도 함께 해제된다. (같은 메모리를 가리킨다.)

이처럼 해제된 대상을 다시 해제하여 생기는 문제를 `double free`라고 한다.

___

이 문제는 객체의 소유권이 명확하지 않기 때문에 발생한다.

해결책으로 `RAII`에 `unique_ptr`라는 동적 할당에 특화된 스마트 포인터가 있다.   
이 스마트 포인터는 \<memory> 라이브러리에 정의되어 있다.

이 포인터는 가리키는 대상에 대한 유일한 소유권을 부여받고,   
이 포인터로만 객체를 소멸시킬 수 있다.

```cpp
#include <memory>

class Test
{
public:
  ~Test()
  {
    std::cout << "Test 소멸자" << std::endl;
  }
};

void func()
{
  throw "exception";
}

int main()
{
  try
  {
    Test *t = new Test;
    std::unique_ptr<Test> ptr(t);
    func();
  }

  catch(const char *e)
  {
    std::cout << e << std::endl;
  }
}


//  Test 소멸자
//  exception
```

> `unique_ptr`의 장점은 자동으로 해제된다는 것이다.   
따라서 `try`를 벗어나자 Test 클래스의 소멸자가 자동으로 호출된다.